module.exports = {
  IN_ATTESA: "IN_ATTESA",
  PAGAMENTO_PENDENTE: "PAGAMENTO_PENDENTE",
  IN_PREPARAZIONE: "IN_PREPARAZIONE",
  COMPLETATO: "COMPLETATO",
  RITIRATO: "RITIRATO",
  ANNULLATO: "ANNULLATO",
  PAGAMENTO_FALLITO: "PAGAMENTO_FALLITO"
};